on:
  push:
    branches:
      - main

name: Deploy

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

jobs:
  deploy:
    defaults:
      run:
        shell: bash
    runs-on: ubuntu-latest
    name: Deploy the SST stack

    steps:
      - uses: actions/checkout@v3
      - id: pnpm-install
        uses: mattwyskiel/sst-node-pnpm-setup@v1
      - run: pnpm i
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: us-east-1
          role-to-assume: ${{secrets.AWS_ROLE_ARN}}
          role-session-name: whiskeyflix-events
      - run: pnpm sst deploy --stage prod --outputs-file outputs.json
        name: Deploy the SST stack
      - uses: mattwyskiel/sst-outputs-to-ssm@main
        name: Upload outputs to AWS SSM
        with:
          outputs_path: .sst/outputs.json
